image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git
    - secondTask  # ветка git


build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x ./gradlew
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true --info


notifications:
  - provider: Email
    # Список адресов
    to:
      - zybu@live.ru
    # Отправлять ли письмо в случае успеха?
    on_build_success: true
    # Отправлять ли письмо в случае провала?
    on_build_failure: false
    # Отправлять ли письмо когда статус изменился?
    on_build_status_changed: false